"""Re-initialization

Revision ID: 4af5c495e406
Revises: 
Create Date: 2026-01-30 19:55:51.751452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4af5c495e406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_monitoring_rules_created_at')
        batch_op.drop_index('ix_monitoring_rules_user_id')

    op.drop_table('monitoring_rules')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_created_at')
        batch_op.drop_index('ix_products_name')
        batch_op.drop_index('ix_products_normalized_name')
        batch_op.drop_index('ix_products_vendor_id')

    op.drop_table('products')
    op.drop_table('sync_metadata')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_created_at')
        batch_op.drop_index('ix_roles_name')

    op.drop_table('roles')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index('ix_vendors_created_at')
        batch_op.drop_index('ix_vendors_name')
        batch_op.drop_index('ix_vendors_normalized_name')

    op.drop_table('vendors')
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_api_call_logs_created_at')
        batch_op.drop_index('ix_api_call_logs_endpoint')
        batch_op.drop_index('ix_api_call_logs_status_code')
        batch_op.drop_index('ix_api_call_logs_timestamp')
        batch_op.drop_index('ix_api_call_logs_user_id')

    op.drop_table('api_call_logs')
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_vulnerabilities_asset_id')
        batch_op.drop_index('ix_asset_vulnerabilities_created_at')
        batch_op.drop_index('ix_asset_vulnerabilities_cve_id')
        batch_op.drop_index('ix_asset_vulnerabilities_status')

    op.drop_table('asset_vulnerabilities')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_assessments_created_at')

    op.drop_table('risk_assessments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_created_at')
        batch_op.drop_index('ix_alerts_cve_id')

    op.drop_table('alerts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_created_at')
        batch_op.drop_index('ix_reports_user_id')

    op.drop_table('reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_api_key')
        batch_op.drop_index('ix_users_created_at')
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_created_at')
        batch_op.drop_index('ix_assets_hostname')
        batch_op.drop_index('ix_assets_ip_address')
        batch_op.drop_index('ix_assets_name')
        batch_op.drop_index('ix_assets_owner_id')

    op.drop_table('assets')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_user_roles_role_id')
        batch_op.drop_index('ix_user_roles_user_id')

    op.drop_table('user_roles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_action')
        batch_op.drop_index('ix_audit_logs_action_timestamp')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_details_gin', postgresql_using='gin')
        batch_op.drop_index('ix_audit_logs_event_id')
        batch_op.drop_index('ix_audit_logs_failed', postgresql_where='(success = false)')
        batch_op.drop_index('ix_audit_logs_resource')
        batch_op.drop_index('ix_audit_logs_resource_type')
        batch_op.drop_index('ix_audit_logs_security', postgresql_where="((action)::text ~~ 'security.%'::text)")
        batch_op.drop_index('ix_audit_logs_severity')
        batch_op.drop_index('ix_audit_logs_timestamp')
        batch_op.drop_index('ix_audit_logs_user_timestamp')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('event_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_audit_logs')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_user_timestamp', ['user_id', sa.text('timestamp DESC')], unique=False)
        batch_op.create_index('ix_audit_logs_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_severity', ['severity'], unique=False)
        batch_op.create_index('ix_audit_logs_security', ['timestamp'], unique=False, postgresql_where="((action)::text ~~ 'security.%'::text)")
        batch_op.create_index('ix_audit_logs_resource_type', ['resource_type'], unique=False)
        batch_op.create_index('ix_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('ix_audit_logs_failed', ['timestamp'], unique=False, postgresql_where='(success = false)')
        batch_op.create_index('ix_audit_logs_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_audit_logs_details_gin', ['details'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_action_timestamp', ['action', sa.text('timestamp DESC')], unique=False)
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name='fk_user_roles_assigned_by_users'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_roles_role_id_roles', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_roles'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('ix_user_roles_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_roles_role_id', ['role_id'], unique=False)

    op.create_table('assets',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_center', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_family', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rto_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rpo_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operational_cost_per_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('installed_software', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('warranty_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_scan_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_assets_owner_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_assets_product_id_products', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_assets_vendor_id_vendors', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_assets'),
    sa.UniqueConstraint('ip_address', 'owner_id', name='uq_asset_ip_owner', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('ix_assets_name', ['name'], unique=False)
        batch_op.create_index('ix_assets_ip_address', ['ip_address'], unique=False)
        batch_op.create_index('ix_assets_hostname', ['hostname'], unique=False)
        batch_op.create_index('ix_assets_created_at', ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('password_reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('api_key_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_login_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('password_reset_token', name='uq_users_password_reset_token', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index('ix_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_users_api_key', ['api_key'], unique=False)

    op.create_table('reports',
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_risk_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generation_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('generation_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('share_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reports_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_reports'),
    sa.UniqueConstraint('share_token', name='uq_reports_share_token', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_reports_created_at', ['created_at'], unique=False)

    op.create_table('alerts',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cve_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name='fk_alerts_acknowledged_by_id_users'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name='fk_alerts_resolved_by_id_users'),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], name='fk_alerts_rule_id_monitoring_rules'),
    sa.PrimaryKeyConstraint('id', name='pk_alerts')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_cve_id', ['cve_id'], unique=False)
        batch_op.create_index('ix_alerts_created_at', ['created_at'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('overall_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vulnerability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exposure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_risk_assessments_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_risk_assessments')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_risk_assessments_created_at', ['created_at'], unique=False)

    op.create_table('asset_vulnerabilities',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cve_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('detected_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detection_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contextual_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remediation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_vulnerabilities_asset_id_assets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='fk_asset_vulnerabilities_assignee_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_asset_vulnerabilities'),
    sa.UniqueConstraint('asset_id', 'cve_id', name='uq_asset_cve', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.create_index('ix_asset_vulnerabilities_status', ['status'], unique=False)
        batch_op.create_index('ix_asset_vulnerabilities_cve_id', ['cve_id'], unique=False)
        batch_op.create_index('ix_asset_vulnerabilities_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_asset_vulnerabilities_asset_id', ['asset_id'], unique=False)

    op.create_table('api_call_logs',
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('api_key_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('request_body_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_api_call_logs')
    )
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.create_index('ix_api_call_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_api_call_logs_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_api_call_logs_status_code', ['status_code'], unique=False)
        batch_op.create_index('ix_api_call_logs_endpoint', ['endpoint'], unique=False)
        batch_op.create_index('ix_api_call_logs_created_at', ['created_at'], unique=False)

    op.create_table('vendors',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('normalized_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('support_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('security_contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vendors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_vendors'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('ix_vendors_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index('ix_vendors_name', ['name'], unique=False)
        batch_op.create_index('ix_vendors_created_at', ['created_at'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_roles')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_name', ['name'], unique=False)
        batch_op.create_index('ix_roles_created_at', ['created_at'], unique=False)

    op.create_table('sync_metadata',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='pk_sync_metadata')
    )
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('normalized_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('version_start', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('version_end', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cpe_string', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('end_of_life', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_products_vendor_id_vendors', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_products'),
    sa.UniqueConstraint('vendor_id', 'name', 'version', name='uq_vendor_product_version', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_vendor_id', ['vendor_id'], unique=False)
        batch_op.create_index('ix_products_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index('ix_products_name', ['name'], unique=False)
        batch_op.create_index('ix_products_created_at', ['created_at'], unique=False)

    op.create_table('monitoring_rules',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('alert_channels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cooldown_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_alerts_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trigger_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schedule_cron', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_monitoring_rules_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_monitoring_rules')
    )
    with op.batch_alter_table('monitoring_rules', schema=None) as batch_op:
        batch_op.create_index('ix_monitoring_rules_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_monitoring_rules_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
