# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local dentro do container
local   all             postgres                                peer
local   all             all                                     md5

# IPv4/IPv6 loopback
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Rede Docker (ajuste para sub-rede específica em produção)
host    all             all             0.0.0.0/0               scram-sha-256